# Generated by Django 5.2.15 on 2026-06-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_key', models.CharField(max_length=64, verbose_name='Misol kaliti')),
                ('preset_name', models.CharField(max_length=128, verbose_name='Misol nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('params', models.JSONField(default=dict, verbose_name='Parametrlar')),
                ('result', models.JSONField(default=dict, verbose_name='Natija')),
                ('method', models.CharField(default='AUTO', max_length=16, verbose_name='Usul')),
                ('n_events', models.IntegerField(default=0, verbose_name='Hodisalar soni')),
                ('success', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli')),
                ('zeno', models.BooleanField(default=False, verbose_name='Zeno chegarasi')),
                ('message', models.TextField(blank=True, default='', verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Simulyatsiya',
                'verbose_name_plural': 'Simulyatsiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
